#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_do_script',
        source='STU_prep.do',
        target=ctx.path_to(ctx, 'OUT_DATA', 'STU_red.dta'),
        name='STU_red'
    )
    ctx(
        features='run_do_script',
        source='PAR_prep.do',
        target=ctx.path_to(ctx, 'OUT_DATA', 'PAR_red.dta'),
        name='PAR_red'
    )
    ctx(
        features='run_do_script',
        source='merge.do',
        target=ctx.path_to(ctx, 'OUT_DATA', 'PISA_data.dta'),
        name='PISA'
    )
