#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_do_script',
        source='STU_prep.do',
        target=ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
        name='get_simulation_draws'
    )
